package company

import "github.com/graphql-go/graphql"

var filterArgs = map[string]*graphql.ArgumentConfig{
	"key":   {Type: graphql.String},
	"value": {Type: graphql.String},
}

var customerCardArgs = map[string]*graphql.ArgumentConfig{
	"No":                      {Type: graphql.NewNonNull(graphql.String)},
	"Name":                    {Type: graphql.String},
	"Address":                 {Type: graphql.String},
	"Address_2":               {Type: graphql.String},
	"Post_Code":               {Type: graphql.String},
	"City":                    {Type: graphql.String},
	"Country_Region_Code":     {Type: graphql.String},
	"Phone_No":                {Type: graphql.String},
	"Contact":                 {Type: graphql.String},
	"VAT_Registration_No":     {Type: graphql.String},
	"Customer_Posting_Group":  {Type: graphql.String},
	"Gen_Bus_Posting_Group":   {Type: graphql.String},
	"VAT_Bus_Posting_Group":   {Type: graphql.String},
	"Global_Dimension_2_Code": {Type: graphql.String},
	"Customer_Price_Group":    {Type: graphql.String},
	"Customer_Disc_Group":     {Type: graphql.String},
	"Payment_Terms_Code":      {Type: graphql.String},
	"Currency_Code":           {Type: graphql.String},
	"Language_Code":           {Type: graphql.String},
	"Web_E_Mail":              {Type: graphql.String},
	"Web_Customer":            {Type: graphql.Boolean},
}

var itemCardArgs = map[string]*graphql.ArgumentConfig{
	"No":                            {Type: graphql.NewNonNull(graphql.String)},
	"Description":                   {Type: graphql.String},
	"Base_Unit_of_Measure":          {Type: graphql.String},
	"Assembly_BOM":                  {Type: graphql.Boolean},
	"Item_Category_Code":            {Type: graphql.String},
	"Product_Group_Code":            {Type: graphql.String},
	"Inventory":                     {Type: graphql.Int},
	"Qty_on_Purch_Order":            {Type: graphql.Int},
	"Qty_on_Sales_Order":            {Type: graphql.Int},
	"Last_Date_Modified":            {Type: graphql.String},
	"Freight_Type":                  {Type: graphql.String},
	"Assembly_Policy":               {Type: graphql.String},
	"Country_Region_of_Origin_Code": {Type: graphql.String},
	"Net_Weight":                    {Type: graphql.Float},
	"Gross_Weight":                  {Type: graphql.Float},
	"Unit_Volume":                   {Type: graphql.Float},
	"Length":                        {Type: graphql.Float},
	"Width":                         {Type: graphql.Float},
	"Height":                        {Type: graphql.Float},
	"Designer":                      {Type: graphql.String},
	"Web_Status":                    {Type: graphql.String},
}

var postShipArgs = map[string]*graphql.ArgumentConfig{
	"No":                          {Type: graphql.String},
	"Sell_to_Customer_No":         {Type: graphql.String},
	"Sell_to_Contact_No":          {Type: graphql.String},
	"Sell_to_Customer_Name":       {Type: graphql.String},
	"Sell_to_Address":             {Type: graphql.String},
	"Sell_to_Address2":            {Type: graphql.String},
	"Sell_to_Post_Code":           {Type: graphql.String},
	"Sell_to_City":                {Type: graphql.String},
	"Sell_to_Contact":             {Type: graphql.String},
	"PEB_Note_of_Goods":           {Type: graphql.String},
	"No_Printed":                  {Type: graphql.Int},
	"Posting_Date":                {Type: graphql.String},
	"Document_Date":               {Type: graphql.String},
	"Requested_Delivery_Date":     {Type: graphql.String},
	"Promised_Delivery_Date":      {Type: graphql.String},
	"Quote_No":                    {Type: graphql.String},
	"Order_No":                    {Type: graphql.String},
	"External_Document_No":        {Type: graphql.String},
	"Salesperson_Code":            {Type: graphql.String},
	"Responsibility_Center":       {Type: graphql.String},
	"Bill_to_Customer_No":         {Type: graphql.String},
	"Bill_to_Contact_No":          {Type: graphql.String},
	"Bill_to_Name":                {Type: graphql.String},
	"Bill_to_Address":             {Type: graphql.String},
	"Bill_to_Address2":            {Type: graphql.String},
	"Bill_to_Post_Code":           {Type: graphql.String},
	"Bill_to_City":                {Type: graphql.String},
	"Bill_to_Contact":             {Type: graphql.String},
	"Shortcut_Dimension_1_Code":   {Type: graphql.String},
	"Shortcut_Dimension_2_Code":   {Type: graphql.String},
	"Ship_to_Code":                {Type: graphql.String},
	"Ship_to_Name":                {Type: graphql.String},
	"Ship_to_Address":             {Type: graphql.String},
	"Ship_to_Address2":            {Type: graphql.String},
	"Ship_to_Post_Code":           {Type: graphql.String},
	"Ship_to_City":                {Type: graphql.String},
	"Ship_to_Country_Region_Code": {Type: graphql.String},
	"Ship_to_Contact":             {Type: graphql.String},
	"Location_Code":               {Type: graphql.String},
	"Outbound_Whse_Handling_Time": {Type: graphql.String},
	"Shipping_Time":               {Type: graphql.String},
	"Shipment_Method_Code":        {Type: graphql.String},
	"Shipping_Agent_Code":         {Type: graphql.String},
	"Shipping_Agent_Service_Code": {Type: graphql.String},
	"Package_Tracking_No":         {Type: graphql.String},
	"Shipment_Date":               {Type: graphql.String},
}

var salesInvoiceArgs = map[string]*graphql.ArgumentConfig{
	"No":                         {Type: graphql.String},
	"Sell_to_Customer_No":        {Type: graphql.String},
	"Sell_to_Contact_No":         {Type: graphql.String},
	"Sell_to_Customer_Name":      {Type: graphql.String},
	"Sell_to_Address":            {Type: graphql.String},
	"Sell_to_Address_2":          {Type: graphql.String},
	"Sell_to_Post_Code":          {Type: graphql.String},
	"Sell_to_City":               {Type: graphql.String},
	"Sell_to_Contact":            {Type: graphql.String},
	"Note_of_Goods":              {Type: graphql.String},
	"Posting_Date":               {Type: graphql.String},
	"Document_Date":              {Type: graphql.String},
	"Salesperson_Code":           {Type: graphql.String},
	"Responsibility_Center":      {Type: graphql.String},
	"Bill_to_Customer_No":        {Type: graphql.String},
	"Bill_to_Contact_No":         {Type: graphql.String},
	"Bill_to_Name":               {Type: graphql.String},
	"Bill_to_Address":            {Type: graphql.String},
	"Bill_to_Address_2":          {Type: graphql.String},
	"Bill_to_Post_Code":          {Type: graphql.String},
	"Bill_to_City":               {Type: graphql.String},
	"Bill_to_Contact":            {Type: graphql.String},
	"Shortcut_Dimension_1_Code":  {Type: graphql.String},
	"Shortcut_Dimension_2_Code":  {Type: graphql.String},
	"Ship_to_Code":               {Type: graphql.String},
	"Ship_to_Name":               {Type: graphql.String},
	"Ship_to_Address":            {Type: graphql.String},
	"Ship_to_Address_2":          {Type: graphql.String},
	"Ship_to_Post_Code":          {Type: graphql.String},
	"Ship_to_City":               {Type: graphql.String},
	"Ship_to_Contact":            {Type: graphql.String},
	"Location_Code":              {Type: graphql.String},
	"Shipment_Method_Code":       {Type: graphql.String},
	"Shipping_Agent_Code":        {Type: graphql.String},
	"Package_Tracking_No":        {Type: graphql.String},
	"Shipment_Date":              {Type: graphql.String},
	"Your_Reference":             {Type: graphql.String},
	"Incoming_Document_Entry_No": {Type: graphql.Int},
	"External_Document_No":       {Type: graphql.String},
	"Campaign_No":                {Type: graphql.String},
	"Assigned_User_ID":           {Type: graphql.String},
	"Job_Queue_Status":           {Type: graphql.String},
	"Status":                     {Type: graphql.String},
	"Payment_Terms_Code":         {Type: graphql.String},
	"Due_Date":                   {Type: graphql.String},
	"Payment_Discount_Percent":   {Type: graphql.Float},
	"Pmt_Discount_Date":          {Type: graphql.String},
	"Payment_Method_Code":        {Type: graphql.String},
	"Direct_Debit_Mandate_ID":    {Type: graphql.String},
	"Prices_Including_VAT":       {Type: graphql.Boolean},
	"VAT_Bus_Posting_Group":      {Type: graphql.String},
	"Credit_Card_No":             {Type: graphql.String},
	"Get_Credit_Card_Number":     {Type: graphql.String},
	"Currency_Code":              {Type: graphql.String},
	"EU_3_Party_Trade":           {Type: graphql.Boolean},
	"Transaction_Type":           {Type: graphql.String},
	"Transaction_Specification":  {Type: graphql.String},
	"Transport_Method":           {Type: graphql.String},
	"Exit_Point":                 {Type: graphql.String},
	"Area":                       {Type: graphql.String},
}

var salesOrderArgs = map[string]*graphql.ArgumentConfig{

	"No":                              {Type: graphql.String},
	"Sell_to_Customer_No":             {Type: graphql.String},
	"Sell_to_Customer_Name":           {Type: graphql.String},
	"Sell_to_Address":                 {Type: graphql.String},
	"Sell_to_Post_Code":               {Type: graphql.String},
	"Sell_to_City":                    {Type: graphql.String},
	"Sell_to_Contact":                 {Type: graphql.String},
	"No_of_Archived_Versions":         {Type: graphql.Int},
	"Customer_No_Web":                 {Type: graphql.String},
	"Posting_Date":                    {Type: graphql.String},
	"Order_Date":                      {Type: graphql.String},
	"Document_Date":                   {Type: graphql.String},
	"Requested_Delivery_Date":         {Type: graphql.String},
	"Promised_Delivery_Date":          {Type: graphql.String},
	"External_Document_No":            {Type: graphql.String},
	"Salesperson_Code":                {Type: graphql.String},
	"Assigned_User_ID":                {Type: graphql.String},
	"Job_Queue_Status":                {Type: graphql.String},
	"Status":                          {Type: graphql.String},
	"Whs_Shipment_Lines_Exists":       {Type: graphql.Boolean},
	"Bill_to_Customer_No":             {Type: graphql.String},
	"Bill_to_Name":                    {Type: graphql.String},
	"Bill_to_Address":                 {Type: graphql.String},
	"Bill_to_Post_Code":               {Type: graphql.String},
	"Bill_to_City":                    {Type: graphql.String},
	"Shortcut_Dimension_2_Code":       {Type: graphql.String},
	"Due_Date":                        {Type: graphql.String},
	"Payment_Discount_Percent":        {Type: graphql.Float},
	"Pmt_Discount_Date":               {Type: graphql.String},
	"Payment_Method_Code":             {Type: graphql.String},
	"Prices_Including_VAT":            {Type: graphql.Boolean},
	"VAT_Bus_Posting_Group":           {Type: graphql.String},
	"Ship_to_Name":                    {Type: graphql.String},
	"Ship_to_Address":                 {Type: graphql.String},
	"Ship_to_Address_2":               {Type: graphql.String},
	"Ship_to_Post_Code":               {Type: graphql.String},
	"Ship_to_City":                    {Type: graphql.String},
	"Ship_to_Country_Region_Code":     {Type: graphql.String},
	"Location_Code":                   {Type: graphql.String},
	"Late_Order_Shipping":             {Type: graphql.Boolean},
	"Shipment_Date":                   {Type: graphql.String},
	"Shipping_Advice":                 {Type: graphql.String},
	"Currency_Code":                   {Type: graphql.String},
	"EU_3_Party_Trade":                {Type: graphql.Boolean},
	"Prepayment_Percent":              {Type: graphql.Float},
	"Compress_Prepayment":             {Type: graphql.Boolean},
	"Prepayment_Due_Date":             {Type: graphql.String},
	"Prepmt_Payment_Discount_Percent": {Type: graphql.Float},
	"Prepmt_Pmt_Discount_Date":        {Type: graphql.String},
}

var salesLineArgs = map[string]*graphql.ArgumentConfig{

	"No":                    {Type: graphql.String},
	"Document_No":           {Type: graphql.String},
	"Type":                  {Type: graphql.String},
	"Description":           {Type: graphql.String},
	"Reserve":               {Type: graphql.String},
	"Quantity":              {Type: graphql.Int},
	"Reserved_Quantity":     {Type: graphql.Int},
	"Unit_of_Measure_Code":  {Type: graphql.String},
	"Unit_Price":            {Type: graphql.Float},
	"Line_Amount":           {Type: graphql.Float},
	"Line_Discount_Percent": {Type: graphql.Float},
	"Line_Discount_Amount":  {Type: graphql.Float},
	"Prepayment_Percent":    {Type: graphql.Float},
	"Prepmt_Line_Amount":    {Type: graphql.Float},
	"Qty_to_Ship":           {Type: graphql.Int},
	"Quantity_Shipped":      {Type: graphql.Int},
	"Qty_to_Invoice":        {Type: graphql.Int},
	"Quantity_Invoiced":     {Type: graphql.Int},
}
